version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A app.workers.tasks worker --loglevel=info
    depends_on:
      - redis
      - app
    env_file:
      - .env
    volumes:
      - .:/app