version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A app.workers.tasks worker --loglevel=info
    depends_on:
      - redis
      - app
    env_file:
      - .env
    volumes:
      - .:/app
