services:
  - type: web
    name: gemini-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis:6379
      - key: CELERY_BROKER_URL
        value: redis://redis:6379
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: gemini-db
    databaseName: gemini
    user: gemini